Repository LuckyVickys/woosan-front, pull requests merged in 2024-06, with the labels that each got.

#1 🔧리액트 초기 설정🔧
  front/.gitignore
  front/README.md
  front/package-lock.json
  front/package.json
  front/public/favicon.ico
  front/public/index.html
  front/public/logo192.png
  front/public/logo512.png
  front/public/manifest.json
  front/public/robots.txt
  front/src/App.css
  front/src/App.js
  front/src/App.test.js
  front/src/components/css/Header.css
  front/src/components/jsx/Footer.jsx
  front/src/components/jsx/Header.jsx
  front/src/index.css
  front/src/index.js
  front/src/join/Join.css
  front/src/join/Join.jsx
  front/src/login/Login.css
  front/src/login/Login.jsx
  front/src/logo.svg
  front/src/main/Main.css
  front/src/main/Main.jsx
  front/src/memberMyPage/myBoardList/MyBoardList.css
  front/src/memberMyPage/myBoardList/MyBoardList.jsx
  front/src/memberMyPage/myGroupList/MyGroupList.css
  front/src/memberMyPage/myGroupList/MyGroupList.jsx
  front/src/memberMyPage/myLikeList/MyLikeList.css
  front/src/memberMyPage/myLikeList/MyLikeList.jsx
  front/src/memberMyPage/myMessageList/MyMessageList.css
  front/src/memberMyPage/myMessageList/MyMessageList.jsx
  front/src/memberMyPage/myReplyList/MyReplyList.css
  front/src/memberMyPage/myReplyList/MyReplyList.jsx
  front/src/memberMyPage/updateInfo/UpdateInfo.css
  front/src/memberMyPage/updateInfo/UpdateInfo.jsx
  front/src/reportWebVitals.js
  front/src/setupTests.js
Labels: 💻 Client, ⚙ Setting

#3 프론트 파일 구조 설정
  front/src/components/MyPage/myBoardList/MyBoardList.jsx
  front/src/components/MyPage/myBoardList/MyBoardList.scss
  front/src/components/MyPage/myLikeList/MyLikeList.jsx
  front/src/components/MyPage/myLikeList/MyLikeList.scss
  front/src/components/MyPage/myMessages/MyMessageList.jsx
  front/src/components/MyPage/myMessages/MyMessageList.scss
  front/src/components/MyPage/myReplyList/MyReplyList.jsx
  front/src/components/MyPage/myReplyList/MyReplyList.scss
  front/src/components/MyPage/updateInfo/UpdateInfo.jsx
  front/src/components/MyPage/updateInfo/UpdateInfo.scss
  front/src/components/common/header/Header.jsx
  front/src/components/common/header/Header.scss
  front/src/components/meeting/add/Add.jsx
  front/src/components/meeting/add/Add.scss
  front/src/components/member/finePW/FindPWModal..scss
  front/src/components/member/finePW/FindPWModal.jsx
  front/src/components/member/join/JoinModal..scss
  front/src/components/member/join/JoinModal.jsx
  front/src/components/member/login/LoginModal..scss
  front/src/components/member/login/LoginModal.jsx
  front/src/components/tip/add/Add.jsx
  front/src/components/tip/add/Add.scss
  front/src/hooks/useAuth.jsx
  front/src/hooks/useFetch.jsx
  front/src/layouts/BasicLayout.jsx
  front/src/layouts/NoneSidebar.jsx
  front/src/layouts/Sidebar.jsx
  front/src/pages/MyPage/UpdateInfoPage.jsx
  front/src/pages/main/MainPage.jsx
  front/src/pages/meeting/common/AddPage.jsx
  front/src/router/root.jsx
  front/src/router/tipRouter.jsx
  front/src/slices/loginSlice.jsx
  front/src/util/cookieUtill.jsx
  front/src/util/jwtUtill.jsx
Labels: 💻 Client, ⚙ Setting

#6 프론트 초기 설정 보완
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/assets/image/Figma.png
  front/src/assets/image/icon-figma.svg
  front/src/assets/image/icon-github.svg
  front/src/assets/image/logo.svg
  front/src/assets/styles/Common.scss
  front/src/assets/styles/Font.scss
  front/src/assets/styles/Header.scss
  front/src/assets/styles/meeting/Add.scss
  front/src/assets/styles/member/FindPWModal..scss
  front/src/assets/styles/member/JoinModal..scss
  front/src/assets/styles/member/LoginModal..scss
  front/src/assets/styles/myPage/MyBoardList.scss
  front/src/assets/styles/myPage/MyLikeList.scss
  front/src/assets/styles/myPage/MyMessageList.scss
  front/src/assets/styles/myPage/MyReplyList.scss
  front/src/assets/styles/myPage/UpdateInfo.scss
  front/src/components/board/add/Add.jsx
  front/src/components/board/add/Add.scss
  front/src/components/common/Area.jsx
  front/src/components/common/Footer.jsx
  front/src/components/common/Header.jsx
  front/src/components/common/Nav.jsx
  front/src/components/common/Sidebar.jsx
  front/src/components/common/header/Header.jsx
  front/src/components/matching/add/Add.jsx
  front/src/components/member/join/JoinModal.jsx
  front/src/components/member/signUp/SignUpModal.jsx
  front/src/layouts/BasicLayout.jsx
  front/src/pages/adminMyPage/ReportList/ReportList.jsx
  front/src/pages/board/ListPage.jsx
  front/src/pages/cs/notices/ListPage.jsx
  front/src/pages/main/MainPage.jsx
  front/src/pages/matchting/common/AddPage.jsx
  front/src/pages/matchting/common/ListPage.jsx
  front/src/pages/meeting/common/AddPage.jsx
  front/src/router/boardRouter.jsx
  front/src/router/root.jsx
  front/src/router/tipRouter.jsx
  package-lock.json
  package.json
Labels: 💻 Client, ⚙ Setting

#8 matching 오타 수정
  front/src/components/common/Sidebar.jsx
  front/src/pages/matching/AddPage.jsx
  front/src/pages/matching/ListPage.jsx
  front/src/pages/matching/SelfAddPage.jsx
  front/src/router/matchingRouter.jsx
  front/src/router/root.jsx
Labels: 🔨 Fix

#10 feat/Roulette 생성
  front/src/assets/image/Polygon 2.png
  front/src/assets/image/coin3.png
  front/src/pages/cs/EventPage.jsx
  front/src/pages/cs/notices/ListPage.jsx
Labels: 💻 Client, 🎨 Html&css

#11 라우터 경로 설정 수정
  front/package-lock.json
  front/package.json
  front/src/assets/styles/Board.scss
  front/src/assets/styles/Common.scss
  front/src/components/board/list/ListTitle.jsx
  front/src/components/common/Nav.jsx
  front/src/components/common/Sidebar.jsx
  front/src/pages/MyPage/IndexPage.jsx
  front/src/pages/MyPage/UpdateInfoPage.jsx
  front/src/pages/board/IndexPage.jsx
  front/src/pages/board/ListPage.jsx
  front/src/pages/cs/EventPage.jsx
  front/src/pages/cs/IndexPage.jsx
  front/src/pages/cs/notices/ListPage.jsx
  front/src/pages/matching/IndexPage.jsx
  front/src/pages/matching/ListPage.jsx
  front/src/router/boardRouter.jsx
  front/src/router/csRouter.jsx
  front/src/router/matchingRouter.jsx
  front/src/router/myPageRouter.jsx
  front/src/router/root.jsx
Labels: 💻 Client, 🔨 Fix, 🎨 Html&css, ⚙ Setting
