Repository LuckyVickys/woosan-front, pull requests merged in 2024-07, with the labels that each got.

#12 fix/Roulette 백엔드 연결
  front/src/pages/cs/EventPage.jsx
Labels: 💻 Client

#13 폰트 변경, 이미지 업로드, 파일명 변경, 검색 바 퍼블리싱 완료
  front/src/assets/image/icon-search.svg
  front/src/assets/styles/Board.scss
  front/src/assets/styles/Common.scss
  front/src/assets/styles/Font.scss
  front/src/components/board/add/Add.jsx
  front/src/components/board/add/Add.scss
  front/src/components/common/PageTitle.jsx
  front/src/components/common/SearchBar.jsx
  front/src/components/common/Sidebar.jsx
  front/src/pages/MyPage/IndexPage.jsx
  front/src/pages/MyPage/UpdateInfoPage.jsx
  front/src/pages/board/IndexPage.jsx
  front/src/pages/cs/IndexPage.jsx
  front/src/pages/matching/IndexPage.jsx
  front/src/router/myPageRouter.jsx
Labels: 💻 Client, ✨ Feature, 🔨 Fix, 🎨 Html&css

#14 feat: 메인페이지 퍼블리싱 진행 중
  front/src/assets/image/main-banner.svg
  front/src/assets/styles/App.scss
  front/src/assets/styles/Common.scss
  front/src/assets/styles/main.scss
  front/src/components/common/Footer.jsx
  front/src/components/common/Header.jsx
  front/src/components/common/Nav.jsx
  front/src/components/common/PageTitle.jsx
  front/src/components/common/SearchBar.jsx
  front/src/components/common/Sidebar.jsx
  front/src/layouts/BasicLayout.jsx
  front/src/pages/main/MainPage.jsx
Labels: 💻 Client, ✨ Feature, 🔨 Fix, 🎨 Html&css

#16 feat: 게시판 상세페이지 퍼블리싱
  front/src/assets/image/heart_no.svg
  front/src/assets/image/heart_yes.svg
  front/src/assets/image/reply_arrow.png
  front/src/assets/image/reply_arrow.svg
  front/src/assets/styles/App.scss
  front/src/assets/styles/board.scss
  front/src/assets/styles/comment.scss
  front/src/components/board/CommentList.jsx
  front/src/components/board/ReadComponent.jsx
  front/src/pages/board/IndexPage.jsx
  front/src/pages/board/ReadPage.jsx
  front/src/router/boardRouter.jsx
Labels: 💻 Client, 🎨 Html&css

#15 fix:메인페이지 레이아웃 완료
  front/src/api/mainApi.jsx
  front/src/assets/image/Figma.png
  front/src/assets/image/heart-icon.svg
  front/src/assets/image/icon-fire.svg
  front/src/assets/image/icon-lamp.svg
  front/src/assets/image/icon-lighting.svg
  front/src/assets/image/icon-lock.svg
  front/src/assets/image/left-button.svg
  front/src/assets/image/main-banner.svg
  front/src/assets/image/right-button.svg
  front/src/assets/styles/main.scss
  front/src/components/main/LikeList.jsx
  front/src/components/main/NoticeList.jsx
  front/src/pages/main/MainPage.jsx
Labels: 💻 Client, 🔨 Fix, 🎨 Html&css

#17 feat: BoardList, select api 연결
  front/src/api/boardApi.js
  front/src/assets/styles/App.scss
  front/src/assets/styles/board2.scss
  front/src/assets/styles/siderbar.scss
  front/src/components/board/AddComponent.jsx
  front/src/components/board/ListComponent.jsx
  front/src/components/board/ModifyComponent.jsx
  front/src/components/board/ReadComponent.jsx
  front/src/components/common/Nav.jsx
  front/src/components/common/SearchBar.jsx
  front/src/components/common/Sidebar.jsx
  front/src/hooks/useCustomMove.jsx
  front/src/pages/board/AddPage.jsx
  front/src/pages/board/IndexPage.jsx
  front/src/pages/board/ListPage.jsx
  front/src/pages/board/ModifyPage.jsx
  front/src/pages/board/ReadPage.jsx
  front/src/router/boardRouter.jsx
  front/src/router/root.jsx
Labels: 💻 Client, 📬 API, ✨ Feature, 🎨 Html&css

#18 fix: 머지 confilct 해결
  front/package-lock.json
  front/package.json
  front/src/assets/styles/App.scss
  front/src/components/board/ReadComponent.jsx
  front/src/components/common/Sidebar.jsx
  front/src/pages/board/IndexPage.jsx
  front/src/pages/board/ReadPage.jsx
  front/src/router/boardRouter.jsx
Labels: 🐞 BugFix

#19 feat: 게시판 상세조회 백엔드 값 적용
  front/src/assets/styles/board.scss
  front/src/components/board/ReadComponent.jsx
Labels: 💻 Client, 📬 API

#20 feat: 메인페이지 공지사항, 인기글 api 연결, board페이지 th 링크 연결
  front/src/api/mainApi.jsx
  front/src/components/board/ListComponent.jsx
  front/src/components/main/LikeList.jsx
  front/src/components/main/NoticeList.jsx
  front/src/index.js
Labels: 💻 Client, 📬 API, 🔨 Fix

#21 fix: 메인 페이지 UI 수정, New모임 퍼블리싱 및 API 작성
  front/src/api/mainApi.jsx
  front/src/assets/image/icon-calendar.svg
  front/src/assets/image/icon-location.svg
  front/src/assets/image/icon-matching.svg
  front/src/assets/image/icon-person.svg
  front/src/assets/image/main-banner.svg
  front/src/assets/styles/main.scss
  front/src/components/main/LikeList.jsx
  front/src/components/main/NewMatchingList.jsx
  front/src/components/main/NoticeList.jsx
  front/src/pages/main/MainPage.jsx
Labels: 💻 Client, 📬 API, 🔨 Fix, 🎨 Html&css

#22 feat: 리스트 호버 등 추가
  front/src/assets/styles/board2.scss
  front/src/components/board/ReadComponent.jsx
  front/src/components/common/Sidebar.jsx
  front/src/hooks/useCustomMove.jsx
  front/src/pages/board/ReadPage.jsx
Labels: 🐞 BugFix, 🔨 Fix, 🎨 Html&css

#23 feat: 댓글 백엔드 연결
  front/src/assets/styles/comment.scss
  front/src/components/board/CommentList.jsx
  front/src/pages/board/ReadPage.jsx
Labels: 💻 Client

#25 fix: readPage 수정
  front/src/pages/board/ReadPage.jsx
Labels: 💻 Client, 🔨 Fix

#26 feat: 댓글 list
  front/src/api/replyApi.js
Labels: 💻 Client, 📬 API

#27 fix: css수정 및 없는댓글 페이징은 안보이게 수정
  front/src/assets/styles/board.scss
  front/src/components/board/CommentList.jsx
Labels: 💻 Client, 🔨 Fix

#28 feat: 드롭다운 퍼블리싱, api버튼 추가
  front/src/assets/image/clova.png
  front/src/assets/image/icon-delete.svg
  front/src/assets/image/icon-modify.svg
  front/src/assets/image/icon-msg.svg
  front/src/assets/image/icon-report.svg
  front/src/assets/image/papago.png
  front/src/assets/image/papago.svg
  front/src/assets/styles/board.scss
  front/src/components/board/BoardDropDown.jsx
  front/src/components/board/CommentDropDown.jsx
  front/src/components/board/CommentList.jsx
  front/src/components/board/ReadComponent.jsx
Labels: 💻 Client, ✨ Feature, 🎨 Html&css

#29 feat: papago 변역
  front/src/api/boardApi.js
  front/src/components/board/ReadComponent.jsx
Labels: 💻 Client, 📬 API

#30 feat: board pagnation컴포넌트, likes 작성, add&modify 작성
  front/src/api/boardApi.js
  front/src/api/likesApi.js
  front/src/api/mainApi.js
  front/src/assets/styles/board2.scss
  front/src/assets/styles/comment.scss
  front/src/components/board/AddComponent.jsx
  front/src/components/board/BoardDropDown.jsx
  front/src/components/board/ListComponent.jsx
  front/src/components/board/ListPageComponent.jsx
  front/src/components/board/ModifyComponent.jsx
  front/src/components/board/PageComponent.jsx
  front/src/components/board/ReadComponent.jsx
  front/src/hooks/useCustomMove.jsx
  front/src/pages/board/AddPage.jsx
  front/src/pages/board/ModifyPage.jsx
  front/src/pages/board/ReadPage.jsx
Labels: 💻 Client, 📬 API, ✨ Feature, 🎨 Html&css

#31 fix: useCustomhook 중복 제거
  front/src/components/board/ReadComponent.jsx
Labels: 🐞 BugFix

#32 feat: 추천 상태 반영
  front/src/api/likesApi.js
  front/src/components/board/BoardDropDown.jsx
  front/src/components/board/ReadComponent.jsx
Labels: 💻 Client, 📬 API, ✨ Feature, 🎨 Html&css

#33 feat: ReadComponent 내 이전, 다음 버튼 구현중
  front/src/components/board/ListComponent.jsx
  front/src/components/board/PageComponent.jsx
  front/src/components/board/ReadComponent.jsx
  front/src/hooks/useCustomMove.jsx
Labels: 💻 Client, ✨ Feature, 🎨 Html&css

#34 feat: 댓글 및 대댓글 드롭다운 수정 및 추가
  front/src/assets/styles/Common.scss
  front/src/assets/styles/siderbar.scss
  front/src/components/board/CommentDropDown.jsx
  front/src/components/board/CommentList.jsx
  front/src/components/common/Sidebar.jsx
Labels: 💻 Client, ✨ Feature, 🔨 Fix, 🎨 Html&css

#35 fix: ReadComponent
  front/src/components/board/ReadComponent.jsx
  front/src/components/common/Sidebar.jsx
Labels: 🐞 BugFix

#36 feat: 게시판 사진 수정 기능
  front/src/components/board/ModifyComponent.jsx
Labels: 💻 Client, 📬 API, ✨ Feature

#37 feat: 게시물 삭제
  front/src/components/board/ModifyComponent.jsx
  front/src/components/board/ReadComponent.jsx
Labels: 💻 Client, 📬 API, ✨ Feature

#38 Feat/reply count
  front/src/assets/styles/board2.scss
  front/src/components/board/ListComponent.jsx
Labels: 💻 Client, ✨ Feature

#39 fix: 댓글 및 대댓글 드롭다운에 모달창 연결
  front/package-lock.json
  front/package.json
  front/src/components/board/CommentDropDown.jsx
  front/src/components/board/CommentList.jsx
  front/src/components/board/MsgModal.jsx
  front/src/components/board/ReportModal.jsx
  front/src/components/member/finePW/FindPWModal.jsx
  front/src/components/member/login/LoginModal.jsx
  front/src/components/member/signUp/SignUpModal.jsx
  front/src/router/matchingRouter.jsx
Labels: 💻 Client, 🔨 Fix, 🎨 Html&css

#43 feat: 댓글 작성, 삭제 기능
  front/src/api/replyApi.js
  front/src/assets/styles/reply.scss
  front/src/components/board/CommentDropDown.jsx
  front/src/components/board/ListComponent.jsx
  front/src/components/board/ReadComponent.jsx
  front/src/components/board/ReplyComponent.jsx
  front/src/components/board/element/ReplyDropDown.jsx
  front/src/util/DateUtil.jsx
Labels: 🐞 BugFix, 💻 Client, 📬 API, ✨ Feature, 🔨 Fix

#41 fix: footer 위치 조정, 사이드바 수정(꿀팁)
  front/src/assets/styles/Common.scss
  front/src/assets/styles/board2.scss
  front/src/assets/styles/main.scss
  front/src/assets/styles/siderbar.scss
  front/src/pages/board/IndexPage.jsx
Labels: 💻 Client, 🔨 Fix, 🎨 Html&css

#45 fix: ReadComponent 내 게시물, 댓글 드롭다운 메뉴 외부 영역 클릭 시 닫김
  front/src/assets/styles/reply.scss
  front/src/components/board/ReadComponent.jsx
  front/src/components/board/ReplyComponent.jsx
  front/src/components/common/Header.jsx
Labels: 💻 Client, 🔨 Fix, 🎨 Html&css

#46 fIx: 로그인 후 헤더, 모달창 퍼블리싱
  front/src/assets/styles/App.scss
  front/src/assets/styles/Common.scss
  front/src/assets/styles/login.scss
  front/src/components/common/Header.jsx
  front/src/components/member/LoginModal.jsx
  front/src/components/member/PWFineModal.jsx
  front/src/components/member/SignUpModal.jsx
Labels: 💻 Client, ✨ Feature, 🔨 Fix, 🎨 Html&css

#47 fix: 폴더명 대소문자 변경
  front/src/components/common/SideBar.jsx
  front/src/components/myPage/myBoardList/MyBoardList.jsx
  front/src/components/myPage/myLikeList/MyLikeList.jsx
  front/src/components/myPage/myMessages/MyMessageList.jsx
  front/src/components/myPage/myReplyList/MyReplyList.jsx
  front/src/components/myPage/updateInfo/UpdateInfo.jsx
  front/src/pages/myPage/IndexPage.jsx
  front/src/pages/myPage/LikePage.jsx
  front/src/pages/myPage/MyBoardPage.jsx
  front/src/pages/myPage/MyMatchingPage.jsx
  front/src/pages/myPage/MyMsgPage.jsx
  front/src/pages/myPage/MyReplyPage.jsx
  front/src/pages/myPage/UpdateInfoPage.jsx
  package-lock.json
Labels: 💻 Client, 🔨 Fix

#48 fix: 드롭다운 오류 수정
  front/src/components/board/ReplyComponent.jsx
Labels: 🐞 BugFix

#49 feat: summaryApi 요약 api 통신 추가
  front/src/api/summaryApi.js
Labels: 💻 Client, 📬 API, ✨ Feature

#50 feat: 쪽지 보내기 모달창 html, css, api 생성(백엔드 연결 전)
  front/src/api/messageApi.js
  front/src/assets/styles/Common.scss
  front/src/assets/styles/login.scss
  front/src/assets/styles/msgModal.scss
  front/src/components/board/element/BoardDropDown.jsx
  front/src/components/board/element/MsgModal.jsx
Labels: 💻 Client, 📬 API, ✨ Feature, 🎨 Html&css

#51 feat:셀프소개팅 리스트 기능 구현
  front/src/assets/styles/matching/FilterBar.module.scss
  front/src/assets/styles/matching/MatchingList.module.scss
  front/src/assets/styles/matching/MatchingPageTemplate.module.scss
  front/src/assets/styles/matching/RegularlyPage.module.scss
  front/src/assets/styles/matching/SelfPage.module.scss
  front/src/components/matching/FilterBar.jsx
  front/src/components/matching/MatchingList.jsx
  front/src/pages/matching/MatchingPage.jsx
  front/src/pages/matching/MatchingPageTemplate.jsx
  front/src/pages/matching/RegularlyPage.jsx
  front/src/pages/matching/SelfPage.jsx
  front/src/pages/matching/TemporaryPage.jsx
Labels: 💻 Client, ✨ Feature, 🎨 Html&css

#53 feat: summary 프론트 구현
  front/src/api/summaryApi.js
  front/src/assets/styles/board.scss
  front/src/components/board/ReadComponent.jsx
Labels: 💻 Client, 📬 API

#55 feat: cs페이지 공지사항 전체조회, (+borad Add 예외처리, useCustomMove수정)
  front/src/api/csApi.js
  front/src/components/board/AddComponent.jsx
  front/src/components/board/ReadComponent.jsx
  front/src/components/cs/NoticeListComponent.jsx
  front/src/components/cs/NoticeReadComponent.jsx
  front/src/hooks/useCustomMove.jsx
  front/src/pages/cs/notices/ListPage.jsx
  front/src/pages/cs/notices/ReadPage.jsx
  front/src/router/csRouter.jsx
Labels: 🐞 BugFix, 💻 Client, 📬 API, ✨ Feature, 🔨 Fix, 🎨 Html&css

#56 feat: 404페이지
  front/src/assets/image/notFound.png
  front/src/assets/styles/Common.scss
  front/src/pages/NotFoundPage.jsx
  front/src/router/boardRouter.jsx
  front/src/router/root.jsx
Labels: 💻 Client, ✨ Feature, 🔨 Fix, 🎨 Html&css

#57 feat: 쪽지 전송 구현
  front/src/api/boardApi.js
  front/src/api/messageApi.js
  front/src/assets/styles/board.scss
  front/src/assets/styles/msgModal.scss
  front/src/assets/styles/reply.scss
  front/src/components/board/ReadComponent.jsx
  front/src/components/board/ReplyComponent.jsx
  front/src/components/board/element/BoardDropDown.jsx
  front/src/components/board/element/MsgModal.jsx
  front/src/components/board/element/ReplyDropDown.jsx
  front/src/components/common/LikeButton.jsx
Labels: 💻 Client, 📬 API, ✨ Feature, 🔨 Fix

#59 Fix/read component
  front/src/components/board/ReadComponent.jsx
  front/src/util/lineConvertUtil.jsx
Labels: 🐞 BugFix, 🔨 Fix, 🎨 Html&css

#60 fix: converter 이름 변경
  front/src/util/convertUtil.jsx
Labels: 🐞 BugFix

#61 Create matching : 정기모임 번개 셀프소개팅 생성 완료 (scss미완료)
  front/package-lock.json
  front/package.json
  front/src/assets/styles/matching/CreateMatching.module.scss
  front/src/assets/styles/matching/FileUpload.module.scss
  front/src/assets/styles/matching/FormField.module.scss
  front/src/assets/styles/matching/LocationField.module.scss
  front/src/assets/styles/matching/MatchingForm.module.scss
  front/src/assets/styles/matching/MatchingPage.module.scss
  front/src/assets/styles/matching/SelfPage.module.scss
  front/src/components/matching/FileUpload.jsx
  front/src/components/matching/FormField.jsx
  front/src/components/matching/LocationField.jsx
  front/src/components/matching/MatchingForm.jsx
  front/src/components/matching/MatchingItem.jsx
  front/src/components/matching/MatchingList.jsx
  front/src/pages/matching/AddPage.jsx
  front/src/pages/matching/CreateMatchingPage.jsx
  front/src/pages/matching/MatchingPage.jsx
  front/src/pages/matching/MatchingPageTemplate.jsx
  front/src/pages/matching/SelfAddPage.jsx
  front/src/pages/matching/SelfPage.jsx
  front/src/router/matchingRouter.jsx
Labels: 💻 Client, ✨ Feature

#62 fix: 회원가입에서 로그인 모달창 이동, 404페이지 레이아웃 적용
  front/src/api/boardApi.js
  front/src/api/messageApi.js
  front/src/api/signUpApi.js
  front/src/assets/styles/Common.scss
  front/src/assets/styles/login.scss
  front/src/components/member/FinePWModal.jsx
  front/src/components/member/LoginModal.jsx
  front/src/components/member/SignUpModal.jsx
  front/src/pages/NotFoundPage.jsx
Labels: 💻 Client, 🔨 Fix, 🎨 Html&css

#63 feat: 게시판, 댓글 작성자 프로필 사진 추가
  front/src/assets/image/profile.png
  front/src/components/board/ReadComponent.jsx
  front/src/components/board/ReplyComponent.jsx
Labels: 💻 Client

#64 fix/ 공지사항 페이지 목록 조회 복구
  front/src/api/csApi.js
  front/src/components/board/element/TableLowComponent.jsx
  front/src/components/cs/NoticeListComponent.jsx
Labels: 🐞 BugFix

#65 fix: 서머리 br태그 반영
  front/src/components/board/ReadComponent.jsx
  front/src/components/cs/NoticeReadComponent.jsx
Labels: 🐞 BugFix

#66 fix: 유효하지 않은 입력 프론트 예외처리
  front/src/assets/styles/board2.scss
  front/src/components/board/AddComponent.jsx
  front/src/components/board/ModifyComponent.jsx
  front/src/util/validationUtil.jsx
Labels: 🐞 BugFix, 💻 Client, 📬 API, ✨ Feature, 🔨 Fix, 🎨 Html&css

#67 feat: develop 브랜치 cicd 반영 1
  front/Dockerfile
  front/nginx.conf
Labels: ⚙ Setting, ✅ Test

#70 fix: develop branch cicd
  front/src/api/csApi.js
Labels: 🐞 BugFix

#68 모임 가입기능 구현중
  front/package-lock.json
  front/package.json
  front/src/api/boardApi.js
  front/src/api/matchingBoardReplyApi.js
  front/src/api/memberMatchingApi.js
  front/src/assets/styles/matching/CommentSection.module.scss
  front/src/assets/styles/matching/MatchingModal.module.scss
  front/src/assets/styles/matching/ReplySection.module.scss
  front/src/components/matching/CommentSection.jsx
  front/src/components/matching/MatchingModal.jsx
  front/src/components/matching/ReplySection.jsx
  front/src/pages/matching/CreateMatchingPage.jsx
  front/src/pages/matching/MatchingPageTemplate.jsx
Labels: 💻 Client, ✨ Feature

#73 feat: 카카오 로그인 구현 중
  front/src/api/kakaoApi.js
  front/src/assets/image/google.svg
  front/src/assets/image/kakao.svg
  front/src/assets/image/naver.svg
  front/src/assets/styles/login.scss
  front/src/components/member/LoginModal.jsx
  front/src/pages/social/KakaoRedirectPage.jsx
  front/src/router/root.jsx
Labels: 💻 Client, 📬 API, ✨ Feature

#69 fix: 쪽지 전송 오류 해결, 예외처리 완료
  front/src/assets/styles/msgModal.scss
  front/src/components/board/ReadComponent.jsx
  front/src/components/board/ReplyComponent.jsx
  front/src/components/board/element/MsgModal.jsx
Labels: 🐞 BugFix, 💻 Client, 🔨 Fix

#74 fix: 댓글 드롭다운 연결, 신고 모달창 코드 수정
  front/src/api/reportApi.js
  front/src/assets/styles/report.scss
  front/src/components/board/ReadComponent.jsx
  front/src/components/board/ReplyComponent.jsx
  front/src/components/board/element/ReplyDropDown.jsx
  front/src/components/board/element/ReportModal.jsx
Labels: 💻 Client, 🔨 Fix

#76 feat: kakao 로그인 시 redirect 설정
  front/src/api/kakaoApi.js
  front/src/pages/social/KakaoRedirectPage.jsx
  front/src/router/root.jsx
Labels: 💻 Client, 📬 API, ✨ Feature

#77 Update ReadComponent.jsx
  front/src/components/board/ReadComponent.jsx
Labels: 🐞 BugFix

#78 Update ReplyComponent.jsx
  front/src/components/board/ReplyComponent.jsx
Labels: 🐞 BugFix

#79 feat: 로그인이 필요한 경우, 로그인 하지 않았을 시 로그인 모달 띄우기(주석으로 올려두었음)
  front/src/components/common/SearchBar.jsx
  front/src/components/member/LoginModal.jsx
  front/src/hooks/useCustomLogin.jsx
  front/src/pages/cs/EventPage.jsx
  front/src/pages/matching/MatchingPage.jsx
Labels: 💻 Client, 📬 API, ✨ Feature

#80 feat: 로그인 시 쿠키 및 상태 저장, 토큰 발급 요청
  front/package-lock.json
  front/package.json
  front/src/hooks/useCustomLogin.jsx
  front/src/slices/loginSlice.jsx
  front/src/util/cookieUtil.jsx
  front/src/util/jwtUtil.jsx
Labels: 💻 Client, 📬 API, ✨ Feature

#82 Feat/search: 검색 자동 완성
  front/src/api/boardApi.js
  front/src/assets/styles/Common.scss
  front/src/components/common/SearchBar.jsx
Labels: 💻 Client, 📬 API

#84 fix: 배포 오류 수정 1
  front/src/api/boardApi.js
Labels: ⚙ Setting

#85 feat: 검색 조건 checked 설정
  front/src/api/boardApi.js
  front/src/components/common/SearchBar.jsx
  front/src/pages/board/IndexPage.jsx
Labels: 💻 Client, 📬 API, ✨ Feature, 🔨 Fix

#86 fix: 로그인 구현
  front/src/api/memberApi.js
  front/src/components/common/Header.jsx
  front/src/components/member/FinePWModal.jsx
  front/src/components/member/LoginModal.jsx
  front/src/components/member/SignUpModal.jsx
  front/src/hooks/useCustomLogin.jsx
Labels: 💻 Client, 📬 API, 🔨 Fix

#87 feat: 로그인 후 헤더 변경
  front/src/api/kakaoApi.js
  front/src/api/memberApi.js
  front/src/assets/styles/Common.scss
  front/src/components/common/Header.jsx
  front/src/components/member/LoginModal.jsx
  front/src/pages/social/KakaoRedirectPage.jsx
  front/src/slices/loginSlice.jsx
Labels: 🐞 BugFix, 💻 Client, 🔨 Fix

#88 feat: 카카오 로그인 시 사용자 정보로 헤더 변경
  front/src/api/kakaoApi.js
  front/src/api/memberApi.js
  front/src/components/common/Header.jsx
  front/src/pages/social/KakaoRedirectPage.jsx
  front/src/slices/loginSlice.jsx
Labels: 💻 Client, 📬 API, ✨ Feature

#89 feat: 회원가입 구현
  front/src/api/memberApi.js
  front/src/assets/styles/login.scss
  front/src/components/member/SignUpModal.jsx
Labels: 💻 Client, 📬 API, ✨ Feature

#90 feat: 유의어 검색어 기능
  front/src/api/boardApi.js
  front/src/components/board/AddComponent.jsx
  front/src/components/board/SearchListComponent.jsx
Labels: 💻 Client, ✨ Feature, 🔨 Fix

#91 feat : MatchingBoard Kakao map api 적용
  front/.gitignore
  front/package-lock.json
  front/package.json
  front/src/api/boardApi.js
  front/src/assets/styles/matching/CommentSection.module.scss
  front/src/assets/styles/matching/CreateMatching.module.scss
  front/src/assets/styles/matching/KakaoMapModal.module.scss
  front/src/assets/styles/matching/LocationField.module.scss
  front/src/assets/styles/matching/MatchingForm.module.scss
  front/src/assets/styles/matching/MatchingItem.module.scss
  front/src/assets/styles/matching/MatchingList.module.scss
  front/src/assets/styles/matching/MatchingModal.module.scss
  front/src/assets/styles/matching/MatchingPage.module.scss
  front/src/assets/styles/matching/ReplySection.module.scss
  front/src/components/matching/CommentSection.jsx
  front/src/components/matching/FileUpload.jsx
  front/src/components/matching/FormField.jsx
  front/src/components/matching/KakaoMapModal.jsx
  front/src/components/matching/LocationField.jsx
  front/src/components/matching/MatchingForm.jsx
  front/src/components/matching/MatchingItem.jsx
  front/src/components/matching/MatchingList.jsx
  front/src/components/matching/MatchingModal.jsx
  front/src/components/matching/ReplySection.jsx
  front/src/pages/matching/CreateMatchingPage.jsx
  front/src/pages/matching/IndexPage.jsx
Labels: 💻 Client, ✨ Feature

#92 feat: 검색어 자동완성(초성검색 포함)
  front/src/api/boardApi.js
  front/src/assets/styles/Common.scss
  front/src/components/common/SearchBar.jsx
Labels: 📬 API, ✨ Feature, 💾 Server

#93 fix: 로그인 시 사용자의 정보 헤더에 표시하도록 수정(일반 로그인, 카카오 로그인 모두 완료)
  front/src/api/memberApi.js
  front/src/components/common/Header.jsx
  front/src/slices/loginSlice.jsx
Labels: 💻 Client, 📬 API, ✨ Feature, 🔨 Fix

#95 feat: 회원가입 예외처리, 비밀번호 보이기 토글
  front/src/api/memberApi.js
  front/src/assets/styles/login.scss
  front/src/components/member/SignUpModal.jsx
  front/src/components/member/TogglePassword.jsx
Labels: 🐞 BugFix, 💻 Client, 📬 API, 🔨 Fix

#97 Feat: profile dropdown 헤더의 프로필 사진 클릭 시 회원정보 드롭다운
  front/src/assets/styles/Common.scss
  front/src/components/common/Header.jsx
  front/src/components/member/LoginModal.jsx
  front/src/components/member/ProfileDropdown.jsx
Labels: 💻 Client, 📬 API, ✨ Feature, 🎨 Html&css

#98 feat : 실시간 검색 순위 구현 (미완)
  front/src/api/boardApi.js
  front/src/assets/styles/Common.scss
  front/src/components/common/Nav.jsx
  front/src/components/common/SearchBar.jsx
Labels: 💻 Client, 📬 API, ✨ Feature, 🔨 Fix

#100 feat: 로그인 하지 않은 상태에서 글쓰기 버튼 누르면 로그인 팝업창 뜨게 설정
  front/src/assets/styles/Common.scss
  front/src/components/common/SearchBar.jsx
Labels: 💻 Client, ✨ Feature

#101 feat: 게시판 회원 정보 적용
  front/src/components/board/AddComponent.jsx
  front/src/components/board/ModifyComponent.jsx
  front/src/components/board/ReadComponent.jsx
  front/src/components/board/ReplyComponent.jsx
  front/src/components/board/element/BoardDropDown.jsx
  front/src/components/common/LikeButton.jsx
Labels: 💻 Client, 📬 API, ✨ Feature

#102 fix: 검색 페이징 처리 완료
  front/src/api/boardApi.js
  front/src/components/board/ListComponent.jsx
  front/src/components/board/SearchListComponent.jsx
  front/src/components/board/element/SearchListPageComponent.jsx
  front/src/components/board/element/TableRowComponent.jsx
  front/src/components/common/SearchBar.jsx
  front/src/components/cs/NoticeListComponent.jsx
  front/src/hooks/useCustomMove.jsx
Labels: 🐞 BugFix, 💻 Client, 📬 API, 🔨 Fix, 🎨 Html&css

#105 test/백서버 연결
  front/src/api/boardApi.js
Labels: ⚙ Setting, ✅ Test

#103 fix: url 변경
  front/src/api/boardApi.js
  front/src/components/board/SearchListComponent.jsx
Labels: 🔨 Fix

#104 fix: 신고창, 모달창으로 로그인한 사용자 id 전달
  front/src/api/messageApi.js
  front/src/components/board/ReadComponent.jsx
  front/src/components/board/element/MsgModal.jsx
  front/src/components/board/element/ReportModal.jsx
Labels: 💻 Client, 🔨 Fix

#106 fix: 비밀번호 성립 조건 수정
  front/src/components/member/SignUpModal.jsx
Labels: 💻 Client, 🔨 Fix

#107 fix: port 번호 변경
  front/src/api/memberApi.js
Labels: 🐞 BugFix, 💻 Client, 📬 API

#108 feat: 비밀번호 찾기 퍼블리싱 추가
  front/src/api/memberApi.js
  front/src/assets/styles/Common.scss
  front/src/assets/styles/login.scss
  front/src/components/member/FinePWModal.jsx
  front/src/components/member/SignUpModal.jsx
Labels: 🐞 BugFix, 💻 Client, 📬 API, ✨ Feature

#109 마이페이지 나의 모임 테스트중
  front/src/api/matchingBoardApi.js
  front/src/assets/styles/matching/FileUpload.module.scss
  front/src/assets/styles/matching/FormField.module.scss
  front/src/assets/styles/matching/KakaoMapModal.module.scss
  front/src/assets/styles/matching/LocationField.module.scss
  front/src/assets/styles/matching/MatchingForm.module.scss
  front/src/assets/styles/matching/MatchingItem.module.scss
  front/src/components/matching/FileUpload.jsx
  front/src/components/matching/KakaoMapModal.jsx
  front/src/components/matching/LocationField.jsx
  front/src/components/matching/MatchingForm.jsx
  front/src/components/matching/MatchingItem.jsx
  front/src/pages/MyPage/MyMatchingPage.jsx
  front/src/pages/matching/CreateMatchingPage.jsx
  front/src/pages/myPage/MyMatchingPage.jsx
Labels: 💻 Client, ✨ Feature

#110 fix: 신고 유형 scss 다시 적용
  front/src/assets/styles/report.scss
Labels: 💻 Client, 🔨 Fix, 🎨 Html&css

#111 feat/내가 작성한 댓글 컴포넌트 (memberId 설정 필요)
  front/src/api/myPageApi.js
  front/src/components/MyPage/myBoardList/MyBoardList.jsx
  front/src/components/MyPage/myLikeList/MyLikeList.jsx
  front/src/components/MyPage/myMessages/MyMessageList.jsx
  front/src/components/MyPage/myReplyList/MyReplyList.jsx
  front/src/components/MyPage/updateInfo/UpdateInfo.jsx
  front/src/components/myPage/ MyReplyComponent.jsx
  front/src/components/myPage/myBoardList/MyBoardList.jsx
  front/src/components/myPage/myLikeList/MyLikeList.jsx
  front/src/components/myPage/myMessages/MyMessageList.jsx
  front/src/components/myPage/myReplyList/MyReplyList.jsx
  front/src/components/myPage/updateInfo/UpdateInfo.jsx
Labels: 💻 Client, 📬 API, 🎨 Html&css

#112 fix: 이름 오류 해결
  front/src/components/myPage/MyReplyComponent.jsx
  front/src/pages/MyPage/MyReplyPage.jsx
  front/src/pages/myPage/MyReplyPage.jsx
Labels: 🐞 BugFix

#114 fix: 비밀번호 찾기 구현
  front/src/api/memberApi.js
  front/src/assets/styles/login.scss
  front/src/components/member/FinePWModal.jsx
  front/src/components/member/LoginModal.jsx
  front/src/components/member/SignUpModal.jsx
Labels: 🐞 BugFix, 💻 Client, 📬 API, 🔨 Fix, 🎨 Html&css

#115 feat: 회원정보 수정 퍼블리싱 완료
  front/src/assets/styles/App.scss
  front/src/assets/styles/updateInfo.scss
  front/src/components/myPage/UpdateInfo.jsx
  front/src/components/myPage/UpdatePassword.jsx
  front/src/pages/myPage/UpdateInfoPage.jsx
Labels: 💻 Client, 🎨 Html&css

#116 feat: 쪽지함 퍼블리싱
  front/src/assets/styles/App.scss
  front/src/assets/styles/myMsg.scss
  front/src/components/myPage/MyMsgComponent.jsx
  front/src/components/myPage/ReadMsgComponent.jsx
  front/src/pages/myPage/MyMsgPage.jsx
Labels: 💻 Client, 🎨 Html&css

#118 fix/ 사이드바 퍼블리싱
  front/src/assets/styles/siderbar.scss
  front/src/components/common/SideBar.jsx
Labels: 🔨 Fix, 🎨 Html&css

#120 fix: 재발급한 비밀번호에 비밀번호 보이기 토글 추가
  front/src/components/member/FinePWModal.jsx
Labels: 💻 Client, 🔨 Fix, 🎨 Html&css

#121 fix: catagory to category 이름 변경
  front/src/assets/styles/Common.scss
  front/src/assets/styles/siderbar.scss
  front/src/components/board/element/PageComponent.jsx
  front/src/components/common/Nav.jsx
  front/src/components/common/SideBar.jsx
Labels: 🐞 BugFix, 🔨 Fix

#124 fix: catagory 오타 수정
  front/src/assets/styles/App.scss
  front/src/assets/styles/sidebar.scss
  front/src/components/common/SearchBar.jsx
  front/src/components/main/LikeList.jsx
  front/src/components/main/NewMatchingList.jsx
  front/src/components/main/NoticeList.jsx
Labels: 🐞 BugFix, 🔨 Fix, 🎨 Html&css

#123 pages에서 myPage 폴더명 소문자로 변경
  front/src/pages/myPage/IndexPage.jsx
  front/src/pages/myPage/IndexPage1.jsx
Labels: 🐞 BugFix

#125 fix: 카테고리 classname 수정
  front/src/assets/styles/main.scss
  front/src/components/common/PageTitle.jsx
  front/src/pages/myPage/IndexPage1.jsx
Labels: 💻 Client, 🔨 Fix

#127 feat/ 검색 순위 구현
  front/src/api/boardApi.js
  front/src/assets/styles/Common.scss
  front/src/components/common/Nav.jsx
  front/src/components/common/RankingList.jsx
Labels: 💻 Client, 📬 API, ✨ Feature, 🔨 Fix

#128 del: front/src/pages/MyPage directory
  front/src/pages/MyPage/LikePage.jsx
  front/src/pages/MyPage/MyBoardPage.jsx
  front/src/pages/MyPage/MyMatchingPage.jsx
  front/src/pages/MyPage/MyMsgPage.jsx
  front/src/pages/MyPage/MyReplyPage.jsx
  front/src/pages/MyPage/UpdateInfoPage.jsx
Labels: 🐞 BugFix, 💻 Client

#129 Del: front/src/pages/adminMyPage/ReportList directory
  front/src/pages/adminMyPage/ReportList/ReportList.jsx
Labels: 🐞 BugFix, 💻 Client

#130 fix: 마이페이지 url에 따른 카테고리 변경
  front/src/pages/myPage/IndexPage.jsx
Labels: 💻 Client, 🔨 Fix

#132 feat: 회원 프로필 등록 및 수정
  front/src/api/memberProfileApi.js
  front/src/assets/styles/updateInfo.scss
  front/src/components/member/ProfileDropdown.jsx
  front/src/components/myPage/UpdateInfo.jsx
  front/src/router/myPageRouter.jsx
Labels: 💻 Client, 📬 API, ✨ Feature

#133 fix: 신고 구현 및 파일 첨부 예외처리
  front/src/components/board/element/ReportModal.jsx
Labels: 💻 Client, 🔨 Fix

#134 fix: reply 넘어가는 id값 맞게 수정
  front/src/components/board/ReplyComponent.jsx
Labels: 🔨 Fix

#135 feat: 포인트 바 복구
  front/src/assets/styles/Common.scss
Labels: 💻 Client, 🎨 Html&css

#136 fix; 댓글 작성자만 삭제 가능하도록 수정
  front/src/components/board/ReplyComponent.jsx
  front/src/components/board/element/ReplyDropDown.jsx
Labels: 💻 Client, 🔨 Fix

#137 fix: 신고 swal창에서 신고 버튼 클릭 후 신고되도록 수정
  front/src/components/board/element/ReportModal.jsx
Labels: 🐞 BugFix, 💻 Client

#139 fix: 회원정보 수정에서 닉네임 중복 체크 기능 추가
  front/src/assets/styles/updateInfo.scss
  front/src/components/myPage/UpdateInfo.jsx
Labels: 💻 Client, 📬 API, 🔨 Fix

#141 fix: 댓글 text 부분 scss 수정, 답글로 변경
  front/src/assets/styles/reply.scss
  front/src/components/board/ReplyComponent.jsx
Labels: 💻 Client, 🔨 Fix, 🎨 Html&css

#142 feat: 사용자 프로필 추가
  front/src/components/common/Header.jsx
  front/src/slices/loginSlice.jsx
Labels: 💻 Client, 📬 API

#143 feat : 매칭 댓글의 답글 설정 완료
  front/src/api/boardApi.js
  front/src/api/matchingBoardReplyApi.js
  front/src/api/memberMatchingApi.js
  front/src/assets/styles/matching/CommentSection.module.scss
  front/src/assets/styles/matching/MatchingForm.module.scss
  front/src/assets/styles/matching/MatchingItem.module.scss
  front/src/assets/styles/matching/MatchingModal.module.scss
  front/src/assets/styles/matching/MatchingReplyDropDown.module.scss
  front/src/assets/styles/matching/ReplySection.module.scss
  front/src/assets/styles/matching/TemporaryPagePage.module.scss
  front/src/components/matching/CommentSection.jsx
  front/src/components/matching/FilterBar.jsx
  front/src/components/matching/MatchingForm.jsx
  front/src/components/matching/MatchingItem.jsx
  front/src/components/matching/MatchingList.jsx
  front/src/components/matching/MatchingModal.jsx
  front/src/components/matching/ReplySection.jsx
  front/src/components/matching/element/MatchingDropDown.jsx
  front/src/components/matching/element/MatchingReplyDropDown.jsx
  front/src/pages/matching/CreateMatchingPage.jsx
  front/src/pages/matching/MatchingPageTemplate.jsx
  front/src/pages/matching/TemporaryPage.jsx
Labels: 💻 Client, ✨ Feature, 🔨 Fix, 🎨 Html&css

#145 Feat/reply profile
  front/src/components/board/ReplyComponent.jsx
  front/src/components/common/Header.jsx
Labels: 💻 Client

#146 feat: 마이페이지 비밀번호 변경 구현
  front/src/assets/styles/updateInfo.scss
  front/src/components/myPage/UpdatePassword.jsx
Labels: 💻 Client, 📬 API, ✨ Feature

#148 feat: 헤더 기본 이미지, 프로필 수정 사용성 테스트
  front/src/assets/styles/Common.scss
  front/src/assets/styles/updateInfo.scss
  front/src/components/common/Header.jsx
  front/src/components/myPage/UpdateInfo.jsx
Labels: 🐞 BugFix, 💻 Client

#149 feat: 마이페이지 쪽지 관련 api 코드 작성
  front/src/api/myPageApi.js
Labels: 💻 Client, 📬 API, ✨ Feature

#154 fix: localhost -> 배포 서버
  front/src/api/kakaoApi.js
  front/src/util/jwtUtil.jsx
Labels: 💻 Client, 📬 API, 🔨 Fix

#158 fix: 마이페이지의 댓글 조회 이동 수정, 관리자페이지 공지사항 리스트 추가
  front/src/components/common/SideBar.jsx
  front/src/components/myPage/MyBoardComponent.jsx
  front/src/components/myPage/MyLikedComponent.jsx
  front/src/components/myPage/MyReplyComponent.jsx
  front/src/pages/adminPage/IndexPage.jsx
  front/src/pages/adminPage/NoticePage.jsx
  front/src/router/adminPageRouter.jsx
Labels: 🐞 BugFix, 💻 Client, 🔨 Fix

#159 feat: 메시지 상세조회 구현 중
  front/src/assets/styles/myMsg.scss
  front/src/components/myPage/MyReceiveMsgComponent.jsx
  front/src/components/myPage/MySendMsgComponent.jsx
  front/src/components/myPage/ReadMsgComponent.jsx
  front/src/hooks/useCustomMsgMove.jsx
  front/src/pages/myPage/IndexPage.jsx
  front/src/pages/myPage/MyMsgPage.jsx
  front/src/router/myPageRouter.jsx
Labels: 💻 Client, 📬 API, ✨ Feature, 🔨 Fix, 🎨 Html&css

#160 fix: 카카오 로그인 키 재발급, .env 파일에 추가
  front/.gitignore
  front/src/api/kakaoApi.js
Labels: 💻 Client, 📬 API, 🔨 Fix

#161 feat: 공지사항 작성
  front/src/components/board/AddComponent.jsx
  front/src/pages/adminPage/AddNoticePage.jsx
  front/src/pages/adminPage/NoticePage.jsx
  front/src/router/adminPageRouter.jsx
Labels: 💻 Client, ✨ Feature

#162 매칭 닉네임과 프로필이미지 구현
  front/src/assets/styles/matching/MatchingModal.module.scss
  front/src/assets/styles/matching/ModifyMatching.module.scss
  front/src/assets/styles/matching/ReplySection.module.scss
  front/src/components/matching/FilterBar.jsx
  front/src/components/matching/MatchingForm.jsx
  front/src/components/matching/MatchingItem.jsx
  front/src/components/matching/MatchingList.jsx
  front/src/components/matching/MatchingModal.jsx
  front/src/components/matching/element/MatchingReplyDropDown.jsx
  front/src/pages/matching/MatchingPageTemplate.jsx
  front/src/pages/matching/ModifyMatchingPage.jsx
  front/src/router/matchingRouter.jsx
Labels: 💻 Client, ✨ Feature, 🎨 Html&css

#163 feat: 메시지 삭제 및 답장 api 통신 구현, 쪽지함 컴포넌트화
  front/src/assets/styles/myMsg.scss
  front/src/components/myPage/MyReceiveMsgComponent.jsx
  front/src/components/myPage/MySendMsgComponent.jsx
  front/src/components/myPage/ReadMsgComponent.jsx
  front/src/components/myPage/element/MyMsgListComponent.jsx
  front/src/components/myPage/element/MyMsgTableRowComponent.jsx
  front/src/components/myPage/element/MyReceiveMsgTableRowComponent.jsx
  front/src/components/myPage/element/MySendMsgTableRowComponent.jsx
Labels: 💻 Client, 📬 API, ✨ Feature

#164 fix: 관리자 페이지, 공지사항 페이지의 컴포넌트 및 scss 수정
  front/src/assets/styles/Common.scss
  front/src/components/board/AddComponent.jsx
  front/src/components/cs/NoticeReadComponent.jsx
  front/src/pages/adminPage/AddNoticePage.jsx
  front/src/pages/adminPage/IndexPage.jsx
  front/src/pages/adminPage/NoticePage.jsx
  front/src/pages/cs/IndexPage.jsx
Labels: 💻 Client, 🔨 Fix, 🎨 Html&css

#166 fix: 공지사항 로우 클릭 소생
  front/src/components/cs/NoticeListComponent.jsx
Labels: 🐞 BugFix

#168 deploy: Docker.File 및 package.json 수정
  front/Dockerfile
  front/package.json
Labels: ⚙ Setting

#167 fix: 로그인에 따른 신고 및 쪽지 기능 숨김 처리
  front/src/components/board/ReadComponent.jsx
  front/src/components/board/ReplyComponent.jsx
  front/src/components/board/element/BoardDropDown.jsx
  front/src/components/board/element/ReplyDropDown.jsx
  front/src/components/cs/NoticeReadComponent.jsx
Labels: 💻 Client, 🔨 Fix

#169 fix: 관리자일 때 드롭다운 수정, 공지사항 번역 기능 추가
  front/src/components/cs/NoticeListComponent.jsx
  front/src/components/cs/NoticeReadComponent.jsx
  front/src/components/member/ProfileDropdown.jsx
Labels: 💻 Client, 📬 API, ✨ Feature, 🔨 Fix

#170 feat: 관리자 페이지에서 공지사항 수정 구현
  front/src/components/board/ModifyComponent.jsx
  front/src/components/board/element/BoardDropDown.jsx
  front/src/components/cs/NoticeListComponent.jsx
  front/src/pages/adminPage/ModifyNoticePage.jsx
  front/src/pages/adminPage/NoticePage.jsx
  front/src/router/adminPageRouter.jsx
Labels: 💻 Client, ✨ Feature, 🔨 Fix

#172 fix: 닉네임 변경을 클릭하지 않으면, 그대로 프로필 변경 진행
  front/src/components/myPage/UpdateInfo.jsx
Labels: 💻 Client, 🔨 Fix

#176 feat: 파파고 번역 완료 시 swal창 띄우기
  front/src/components/board/ReadComponent.jsx
Labels: 💻 Client, 🎨 Html&css

#177 fix: 신고유형 및 처리 여부 수정, 페이지네이션
  front/src/components/adminPage/ReportListComponent.jsx
  front/src/components/adminPage/element/TableRowComponent.jsx
  front/src/hooks/useCustomReportMove.jsx
Labels: 💻 Client, 🔨 Fix

#178 feat: 관리자 페이지 신고 상세 보기 구현
  front/src/api/adminApi.js
  front/src/assets/styles/App.scss
  front/src/assets/styles/readReport.scss
  front/src/components/adminPage/ReportReadComponent.jsx
  front/src/pages/adminPage/ReportReadPage.jsx
  front/src/router/adminPageRouter.jsx
Labels: 💻 Client, 📬 API, ✨ Feature

#183 fix: 회원정보 드롭다운 바깥 부분 클릭하면 닫히도록 수정
  front/src/components/common/Header.jsx
Labels: 💻 Client, 🔨 Fix

#184 refactor: 인기글 및 공지사항 제목 15자 제한, 글씨 안 깨지게 처리
  front/src/assets/styles/common.scss
  front/src/assets/styles/main.scss
  front/src/components/main/LikeList.jsx
  front/src/components/main/NoticeList.jsx
Labels: 💻 Client, 🔨 Fix, 🎨 Html&css

#185 feat:관리자 배너 사진 관리
  front/src/api/adminApi.js
  front/src/pages/adminPage/UploadPage.jsx
Labels: 💻 Client, 📬 API, ✨ Feature

#186 refactor: 글씨 안 깨지게 처리
  front/src/assets/styles/board.scss
  front/src/assets/styles/board2.scss
  front/src/assets/styles/login.scss
  front/src/assets/styles/myMsg.scss
  front/src/assets/styles/reply.scss
  front/src/assets/styles/sidebar.scss
Labels: 💻 Client, 🔨 Fix, 🎨 Html&css

#188 feat: 신고글 바로가기 기능, 신고 처리 완료 기능
  front/src/api/adminApi.js
  front/src/components/adminPage/ReportReadComponent.jsx
Labels: 💻 Client, 📬 API, ✨ Feature

#189 fix: banner.scss 수정 및 중복 코드 제거
  front/src/assets/styles/App.scss
  front/src/assets/styles/banner.scss
  front/src/assets/styles/main.scss
  front/src/components/adminPage/element/ListPageComponent.jsx
  front/src/components/main/Banner.jsx
Labels: 💻 Client, 🔨 Fix, 🎨 Html&css

#190 feat: 쪽지 상세 조회에 신고 모달창 연결
  front/src/components/board/element/ReportModal.jsx
  front/src/components/myPage/ReadMsgComponent.jsx
  front/src/pages/adminPage/IndexPage.jsx
Labels: 💻 Client, ✨ Feature

#193 fix: 리팩토링, 메서드명 변수명 변경, 랭킹 퍼블리싱 변경
  front/src/api/adminApi.js
  front/src/api/boardApi.js
  front/src/api/csApi.js
  front/src/api/replyApi.js
  front/src/assets/styles/common.scss
  front/src/components/board/AddComponent.jsx
  front/src/components/board/ModifyComponent.jsx
  front/src/components/board/ReplyComponent.jsx
  front/src/components/board/element/ReplyDropDown.jsx
  front/src/components/common/RankingList.jsx
  front/src/components/cs/NoticeListComponent.jsx
Labels: 🔨 Fix, 🎨 Html&css

#194 fix: 매인 페이지 인기글과 공지사항 클릭 이벤트
  front/src/components/main/LikeList.jsx
  front/src/components/main/NoticeList.jsx
  front/src/components/main/element/TableRowComponent.jsx
Labels: 💻 Client, 🔨 Fix

#195 feat: 로그인 하지 않았을 시 마이페이지 클릭시 로그인 모달 뜨게
  front/src/components/common/Nav.jsx
  front/src/hooks/useCustomLogin.jsx
Labels: 💻 Client, ✨ Feature

#196 fix:공지사항 줄바꿈 수정 및 뒤로가기 버튼 추가
  front/src/components/board/ReadComponent.jsx
  front/src/components/board/element/ListButton.jsx
  front/src/components/common/BackButton.jsx
  front/src/components/cs/NoticeReadComponent.jsx
  front/src/components/main/NoticeList.jsx
  front/src/hooks/useCustomMove.jsx
Labels: 💻 Client, 🔨 Fix

#197 feat: 로그인 안 했을 시 모임 개설 클릭하면 로그인 모달 뜨게 처리
  front/src/components/common/Nav.jsx
  front/src/hooks/useCustomLogin.jsx
  front/src/pages/matching/MatchingPage.jsx
  front/src/pages/matching/RegularlyPage.jsx
  front/src/pages/matching/SelfPage.jsx
  front/src/pages/matching/TemporaryPage.jsx
Labels: 💻 Client, ✨ Feature

#198 feat: 로그인 안 했을 시 swal, 로그인 모달 처리
  front/src/components/board/ReadComponent.jsx
  front/src/components/board/element/BoardDropDown.jsx
  front/src/components/board/element/ReplyDropDown.jsx
Labels: 💻 Client, ✨ Feature

#199 fix: 프로필 드롭다운 USER일 때만 레벨, 포인트 보이도록 수정
  front/src/components/member/ProfileDropdown.jsx
Labels: 💻 Client, 🔨 Fix

#200 fix: board css 깨지는 것 수정
  front/src/assets/styles/board.scss
Labels: 🐞 BugFix, 🔨 Fix

#201 fix: 신고글 바로가기 기능 수정
  front/src/api/adminApi.js
  front/src/components/adminPage/ReportReadComponent.jsx
  front/src/components/adminPage/element/TableRowComponent.jsx
Labels: 💻 Client, 🔨 Fix

#202 fix: 회원정보에 변경이 있을 시 프로필 드롭다운 정보도 수정되게 처리, 마이페이지 메시지 삭제 post에서 put으로 변경
  front/src/api/myPageApi.js
  front/src/assets/styles/common.scss
  front/src/components/common/Header.jsx
  front/src/components/member/ProfileDropdown.jsx
Labels: 💻 Client, 📬 API, 🔨 Fix, 🎨 Html&css

#204 fix: 회원 정보 수정 시 swal창 오픈 후 reload, 글자 수 제한, 댓글 내용 줄바꿈
  front/src/assets/styles/reply.scss
  front/src/components/adminPage/element/TableRowComponent.jsx
  front/src/components/board/element/TableRowComponent.jsx
  front/src/components/myPage/UpdateInfo.jsx
  front/src/components/myPage/UpdatePassword.jsx
  front/src/components/myPage/element/MyBoardTableRowComponent.jsx
  front/src/components/myPage/element/MyMsgListComponent.jsx
  front/src/components/myPage/element/MyRepliesTableRowComponent.jsx
Labels: 💻 Client, 🔨 Fix, 🎨 Html&css

#206 feat: 회원가입 모달창에 인증 코드 입력칸 퍼블리싱
  front/src/assets/styles/login.scss
  front/src/components/member/SignUpModal.jsx
Labels: 💻 Client, ✨ Feature, 🎨 Html&css

#207 fix: 마이페이지 회원 정보 수정에 소개 퍼블리싱
  front/src/components/myPage/UpdateInfo.jsx
Labels: 💻 Client, 🔨 Fix, 🎨 Html&css
